app = "aab-api"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

[[services.ports]]
  port = 3000
  handlers = ["http"]

[deploy]
  release_command = "npm run build"
  
[processes]
  app = "node packages/api/src/index.js"
